### ISSUE TITLE
Labels on top ?

### ISSUE THREAD

**Issue by shaq2001** [thierryVergult/CandyPie#10]
Really nice work, how about an option to have labels on top, and maybe automatically put them on top when the height gets too small ?

**Comment by thierryVergult** [comment]
Thanks for the suggestion. The label handling needs an overhaul, and in case of too small height you can consider it even as a bug.

**Comment by thierryVergult** [comment]
@shaq2001 : you can now set the _addLegend_ configuration option. This adds a horizontal legend below the Candy Pie canvas. This can be a temporary solution for having info (labels) about low slices.

**Comment by thierryVergult** [comment]
Last release brought hover functionality, which you can configure via
- hoverShowLabel : default false
- hoverShowHeight : default false
- hoverShowArcPct : default false

So in case of slices being too low to contain a label, you can set **sliceShowLabel** to false (is the default, PS;: new name, was showLabel before).

And then see the labels via the new hover feature, and/or via the legend.

ps: the JavaScript call also changed with this release : **candyPie.babylon** is now needed, instead of the previous *candy_pie_babylon*

Hope this helps

**Comment by shaq2001** [comment]
very nice, thanks for efforts, will probably use this in my apex application, will credit & let you know.

**Comment by thierryVergult** [comment]
You're welcome.

out of curiosity, are you talking about Oracle Apex (which I know pretty well), or the language within Salesforce?

**Comment by shaq2001** [comment]
yeah, oracle apex :) i put it in a dynamic content region and used in the style of:

frontend_pkg.get_3d_pie(
                p_arg1 => 'pie2',
                p_arg2 => 'height:13vh;width:15vh;',
                p_arg3 => 'slices: [
                  { height: 0.5, color: ''lightgray'', label: ''  Weight''},
                  { height: 0.5, color: ''#f8f6e1'',   label: ''   BMI''},
                  { height: 0.5, color: ''lightgray'', label: '' Lean BM''},
                  { height: 0.5, color: ''#f8f6e1'',   label: '' Fat\nBM''}
                ],
                spaceBetweenSlices: true,
                innerRadiusPct: 0, // use 0 to get rid of the donut hole
                showLabel: true,
                labelFontFactor: 2.5,
                labelExtraTopMargin: 60,
                labelColor: ''rgb(155, 102, 102)'',
                backgroundColor: ''rgb(196,238,216)'', // green-ish <- disabled in code (transparent)
                clickScalePct: 0,
                verticalFactor: 1.6,
                allowVerticalRotation : true,
                cameraDegreesY: 20,
                secondsPerRotation: 80};',
                p_arg4 => 'arg4',
                p_arg5 => 'arg5');
                
 
 - a bit sloppy to put all in argument 3, but thats how it is for now at least.
 i'll be happy give you a tour when its ready if you're interested!

**Comment by thierryVergult** [comment]
Any JavaScript client can use this solution, but funny that one of the first implementations I'm aware of is using it from Apex/ plsql.

Good luck with it!
